### ISSUE TITLE
PDMIFQUANTILE() fails when # factors < 2

### ISSUE THREAD

**Issue by SvN-HEC** [Tomohiro-Ando/PDMIF#1]
The title says it all.
Error message is 
```
  Error in Fac[i, ] <- (fit$coefficients)[1:Nfactors] : 
    incorrect number of subscripts on matrix
```

Example:
```
    library(PDMIF)
    fit <- PDMIFQUANTILE(data7X,data7Y,0.5,2)
    fit2 <- PDMIFQUANTILE(data7X,data7Y,0.5,1)
```

**Comment by Tomohiro-Ando** [comment]
Thanks for highlighting.

The code has been adjusted to allow for Nfactors = 1

**Comment by SvN-HEC** [comment]
Thank you, Tomohiro.

I was also wondering whether you might be able to provide a reference for testing

  *   null hypotheses on the number of factors, or
  *   the null hypothesis of homogeneity of the regression coefficients
in the case of panel quantile regressions (i.e. PDMIFQUANTILE() ), as this appears to go beyond the cases considered in Ando and Bai (2015).

Again, many thanks for making this package available.

Sincerely,

Simon van Norden
HEC Montréal
________________________________
